### ISSUE TITLE
How do you mention Python version?

### ISSUE THREAD

**Issue by sameerkumar18** [digitalocean/sample-python#5]
I think the default Python version is 3.8. I want it to be 3.6...Should I create a runtime.txt like in Heroku?
Thanks!

**Comment by sameerkumar18** [comment]
runtime.txt did work but I got stuck in another issue with Gunicorn's permission
I ended up using Caprover. 
Would be really helpful if there was some Heroku migration documentation 
![Screenshot 2020-10-15 at 3 50 33 AM](https://user-images.githubusercontent.com/15978864/96051638-9656fb00-0e99-11eb-89e3-bc0fe5a5bb68.png)

**Comment by MasonEgger** [comment]
So this is a known problem with gunicorn. You can solve this by adding the `--worker-tmp-dir` flag to your command like this ` gunicorn --worker-tmp-dir /dev/shm mysite.wsgi.`

And yes, a runtime.txt will allow you to specify the python version. 

Let us know if this works for you.
